import Head from 'next/head';
import Link from 'next/link';

function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <article>
        <div>
          <Link href="/scroll-animation">
            <a>Scroll Animation</a>
          </Link>
        </div>
      </article>
    </div>
  );
}

export default Home;
